feat: changes ENG-1110 ENG-1109 ENG-1087
turntable-so/turntable pull request #72
Opened 2024-09-02 02:56 UTC by ccgomezn

2024-09-04 14:20 UTC, ianrtracey requested changes

2024-09-05 15:14 UTC, ianrtracey commented on frontend/src/app/fetcher.ts
> +    console.log("body", body)
can we remove this?

2024-09-05 15:15 UTC, ianrtracey commented on frontend/src/app/url.ts
> +    return process.env.NEXT_PUBLIC_BACKEND_HOST || (typeof window === "undefined" ? "http://localhost:8000" : "http://localhost:8000")
are you running the docker compose instance with the frontend inside of it as well? I think this will break that bc we use docker's DNS

2024-09-05 15:17 UTC, ianrtracey approved these changes

2024-09-05 17:39 UTC, ccgomezn commented on frontend/src/app/url.ts
> +    return process.env.NEXT_PUBLIC_BACKEND_HOST || (typeof window === "undefined" ? "http://localhost:8000" : "http://localhost:8000")
oh you are right moving back the change, i think this code was pushed by mistake

2024-09-05 17:51 UTC, merged